name = "VrpAnt"
uuid = "33562f98-8851-4f19-a644-1cbda2426bff"
authors = ["Lucas Baussay"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
